## Manipulating and Comparing arrays

### Arithmetic

In [1]:
import numpy as np
a1=np.arange(1,4)

In [2]:
a1

array([1, 2, 3])

In [3]:
ones=np.ones(3)

In [4]:
 a1+ones,a1-ones

(array([2., 3., 4.]), array([0., 1., 2.]))

In [5]:
a2=np.array([[1,2,3.3],[4,10,19.5]])

In [6]:
a2

array([[ 1. ,  2. ,  3.3],
       [ 4. , 10. , 19.5]])

In [7]:
a1

array([1, 2, 3])

In [8]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 20. , 58.5]])

In [9]:
a3=np.random.randint(19,size=(2,2,3))

In [10]:
a3

array([[[11, 11, 12],
        [ 6, 15, 16]],

       [[ 7, 10, 13],
        [13, 10,  7]]])

In [11]:
a2*a3

array([[[ 11. ,  22. ,  39.6],
        [ 24. , 150. , 312. ]],

       [[  7. ,  20. ,  42.9],
        [ 52. , 100. , 136.5]]])

In [12]:
a2//a1

array([[1., 1., 1.],
       [4., 5., 6.]])

In [13]:
a2**a1

array([[1.000000e+00, 4.000000e+00, 3.593700e+01],
       [4.000000e+00, 1.000000e+02, 7.414875e+03]])

### Aggregation

In [14]:
lis=[1,2,3]
type(lis)

list

In [15]:
sum(lis)

6

In [16]:
a1

array([1, 2, 3])

In [17]:
np.sum(a1) #sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays(`np.sum()`).

In [18]:
#create a massive Numpy array
lar=np.random.random(1000)

In [19]:
lar

array([9.46542351e-01, 9.14497378e-01, 3.99750684e-01, 5.27714463e-01,
       8.77782348e-01, 6.76241015e-01, 5.66772554e-01, 9.88102502e-01,
       3.45029902e-01, 4.68535435e-01, 7.61623645e-01, 3.57189792e-01,
       1.17553875e-01, 8.34407851e-01, 3.09600876e-02, 6.18150720e-01,
       7.11558640e-02, 5.80683523e-01, 5.71428578e-01, 6.15384226e-01,
       1.41156725e-01, 4.80240260e-01, 8.22030025e-01, 7.73801689e-01,
       2.55758426e-03, 6.87554823e-01, 2.27489909e-01, 1.66377573e-01,
       9.33151367e-01, 6.15525872e-01, 1.97111336e-01, 6.82798408e-01,
       1.38288241e-01, 4.20641916e-01, 1.76944327e-01, 6.66142206e-02,
       3.45250890e-02, 6.92446428e-01, 1.82810552e-01, 7.14920951e-01,
       5.28420282e-01, 9.92201197e-01, 2.04883061e-01, 6.77774047e-01,
       5.56510561e-01, 3.92350583e-01, 6.16541106e-01, 4.05543736e-01,
       8.58174915e-01, 5.45829898e-01, 4.05872065e-01, 6.26543040e-01,
       4.70553106e-01, 6.51713579e-01, 7.46380418e-01, 5.79311542e-01,
      

In [20]:
%timeit sum(lar)

50.6 µs ± 2.11 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [21]:
%timeit np.sum(lar)

2.42 µs ± 103 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [22]:
a2

array([[ 1. ,  2. ,  3.3],
       [ 4. , 10. , 19.5]])

In [23]:
np.mean(a2)

6.633333333333333

In [24]:
np.min(a2)

1.0

In [25]:
np.max(a2)

19.5

In [26]:
#Standard Deviation
np.std(a2)

6.430828527923564

In [27]:
#Variance
np.var(a2)

41.355555555555554

Standard Deviation and Variace

In [28]:
hvar=np.array([ 1,100,200,300,4000,5000])
lvar=np.array([2,4,6,8,10])

In [29]:
np.var(hvar)

4296133.472222221

In [30]:
np.var(lvar)

8.0

In [31]:
np.mean(hvar)

1600.1666666666667

## Reshaping and Transposing

In [32]:
a2

array([[ 1. ,  2. ,  3.3],
       [ 4. , 10. , 19.5]])

In [33]:
a2.shape

(2, 3)

In [34]:
a2.reshape(3,2)

array([[ 1. ,  2. ],
       [ 3.3,  4. ],
       [10. , 19.5]])

In [35]:
 a3 

array([[[11, 11, 12],
        [ 6, 15, 16]],

       [[ 7, 10, 13],
        [13, 10,  7]]])

In [36]:
a3.shape

(2, 2, 3)

In [43]:
a4=np.random.randint(5,size=(2,2))

In [45]:
a4.reshape(2,2,1)

array([[[3],
        [1]],

       [[2],
        [2]]])

In [46]:
a3*a4.reshape(2,2,1)

array([[[33, 33, 36],
        [ 6, 15, 16]],

       [[14, 20, 26],
        [26, 20, 14]]])

In [47]:
a2

array([[ 1. ,  2. ,  3.3],
       [ 4. , 10. , 19.5]])

In [48]:
#Transpose of a matrix
a2.T

array([[ 1. ,  4. ],
       [ 2. , 10. ],
       [ 3.3, 19.5]])

In [54]:
a3

array([[[11, 11, 12],
        [ 6, 15, 16]],

       [[ 7, 10, 13],
        [13, 10,  7]]])

In [55]:
a3.T.shape,a3.T

((3, 2, 2),
 array([[[11,  7],
         [ 6, 13]],
 
        [[11, 10],
         [15, 10]],
 
        [[12, 13],
         [16,  7]]]))

# DoT Product

In [64]:
#1-D--inner product of vectors without complex conjugation
np.random.seed(1)
import pandas as pd
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))

In [65]:
mat1

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [66]:
mat2

array([[2, 4, 7],
       [7, 9, 1],
       [7, 0, 6],
       [9, 9, 7],
       [6, 9, 1]])

In [67]:
np.dot(mat1,mat2.T) #but mat1 * mat2(np.multiply(a,b)) gives element wise multiplication

array([[105, 116,  89, 180, 111],
       [ 10,  35,  35,  45,  30],
       [ 72,  76,  43, 114,  75],
       [ 54,  85,  87, 127,  76],
       [ 46,  57,  59,  91,  52]])

In [68]:
sales_amount=np.random.randint(20,size=(5,3))
sales_amount

array([[ 0, 17,  8],
       [13, 19, 15],
       [10,  8,  7],
       [ 3,  6, 17],
       [ 3,  4, 17]])

In [69]:
weekly_sales=pd.DataFrame(sales_amount,index=['Mon','Tues','Wed','Thurs','Fri'],columns=['Almond Butter','Peanut Butter','Cashew Butter',])

In [70]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon                0             17              8
Tues              13             19             15
Wed               10              8              7
Thurs              3              6             17
Fri                3              4             17

In [71]:
#Create prices array
prices=np.array([10,8,12])

In [73]:
#Create butter prices DataFrame
butter_prices=pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=['Almond Butter','Peanut Butter','Cashew Butter'])

In [74]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [76]:
total_sales=prices.dot(sales_amount.T)

In [77]:
total_sales

array([232, 462, 248, 282, 266])

In [78]:
#Create daily_sales
weekly_sales['Total']=total_sales

In [79]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total
Mon                0             17              8    232
Tues              13             19             15    462
Wed               10              8              7    248
Thurs              3              6             17    282
Fri                3              4             17    266

### Comparison Operators

In [80]:
a1

array([1, 2, 3])

In [81]:
a2

array([[ 1. ,  2. ,  3.3],
       [ 4. , 10. , 19.5]])

In [83]:
a1==a2,a1>a2

(array([[ True,  True, False],
        [False, False, False]]),
 array([[False, False, False],
        [False, False, False]]))

In [84]:
a1<5

array([ True,  True,  True])

In [85]:
a1>5

array([False, False, False])

## Sorting Arrays

In [86]:
r_array=np.random.randint(10,size=(3,5))

In [87]:
r_array

array([[4, 0, 3, 9, 2],
       [0, 4, 9, 2, 7],
       [7, 9, 8, 6, 9]])

In [88]:
np.sort(r_array)#it'll sort by rows

array([[0, 2, 3, 4, 9],
       [0, 2, 4, 7, 9],
       [6, 7, 8, 9, 9]])

In [89]:
np.argsort(r_array) #gives the indices of the sorted array

array([[1, 4, 2, 0, 3],
       [0, 3, 1, 4, 2],
       [3, 0, 2, 1, 4]], dtype=int64)

In [90]:
a1

array([1, 2, 3])

In [91]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [92]:
np.argmin(a1)

0

In [93]:
np.argmax(a1)

2

In [96]:
r_array

array([[4, 0, 3, 9, 2],
       [0, 4, 9, 2, 7],
       [7, 9, 8, 6, 9]])

In [97]:
np.argmax(r_array,axis=0)

array([2, 2, 1, 0, 2], dtype=int64)

In [98]:
np.argmax(r_array,axis=1)

array([3, 2, 1], dtype=int64)

## Practical Example - Numpy in action

In [103]:
#turn image into a numpy array
from matplotlib.image import imread
panda=imread('panda.png')

In [105]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [106]:
panda*2

array([[[0.10980392, 0.21176471, 0.13333334],
        [0.10980392, 0.21176471, 0.13333334],
        [0.10980392, 0.21176471, 0.13333334],
        ...,
        [0.32941177, 0.25882354, 0.1882353 ],
        [0.32941177, 0.25882354, 0.1882353 ],
        [0.32941177, 0.25882354, 0.1882353 ]],

       [[0.10980392, 0.21176471, 0.13333334],
        [0.10980392, 0.21176471, 0.13333334],
        [0.10980392, 0.21176471, 0.13333334],
        ...,
        [0.32941177, 0.25882354, 0.1882353 ],
        [0.32941177, 0.25882354, 0.1882353 ],
        [0.32941177, 0.25882354, 0.1882353 ]],

       [[0.10980392, 0.21176471, 0.13333334],
        [0.10980392, 0.21176471, 0.13333334],
        [0.10980392, 0.21176471, 0.13333334],
        ...,
        [0.32941177, 0.25882354, 0.1882353 ],
        [0.32941177, 0.25882354, 0.1882353 ],
        [0.32941177, 0.25882354, 0.1882353 ]],

       ...,

       [[0.26666668, 0.14901961, 0.10980392],
        [0.24313726, 0.1254902 , 0.08627451],
        [0.21960784, 0